package-lock.json
package.json
src/FancyButton.ts

There where some edge cases of positioning icon and text inside the button active view, that where fixed.
Also some animation fixes where applied.
And 1 improvement to a FancyButton override methods.
Also FancyButton docs where improved a bit.

Fix button offset and anchor issues

---

src/Layout.ts
src/stories/layout/LayoutDefault.stories.ts
src/stories/layout/LayoutHorizontal.stories.ts
src/stories/layout/LayoutVertical.stories.ts

Fixed an issue where layout would error out if no type was set.
Set default to "vertical", feel free to change. 
Also added 3 storybook stories for Layout (Default, Vertical, Horizontal). 
Fixes #43

Layout fixes

---

src/Button.ts
src/Input.ts
src/ScrollBox.ts
src/SliderBase.ts
src/utils/helpers/hitbox.ts

v7.2.0 introduce `eventMode` which solved our problem of having to remove the hit area of objects
https://github.com/pixijs/pixijs/releases/tag/v7.2.0

Use eventMode

---

src/SliderBase.ts

Single slider throws an error:
```
TypeError: Cannot set properties of undefined (setting 'eventMode')
```

Fix single slider

---

src/Button.ts
src/ButtonEvents.ts
src/CheckBox.ts
src/DoubleSlider.ts
src/FancyButton.ts
src/Input.ts
src/List.ts
src/MaskedFrame.ts
src/ProgressBar.ts
src/RadioGroup.ts
src/ScrollBox.ts
src/Select.ts
src/Slider.ts
src/SliderBase.ts
src/Switcher.ts
src/utils/trackpad/ScrollSpring.ts
src/utils/trackpad/SlidingNumber.ts
src/utils/trackpad/Spring.ts
src/utils/trackpad/Trackpad.ts

Closes #53 
Also `public` was removed for consistency, as it was present somewhere and somewhere - not.

Update private with protected

---

src/ScrollBox.ts

70 scrollBox.destroy does not destroy the ticker

---

src/List.ts

72 How to use bidirectional List?

---

src/FancyButton.ts

fix Hover on buttons on mobile devices #59

---

src/Input.ts

Multi input not work correctly on mobile #35

---

src/CircularProgressBar.ts
src/stories/progressBar/ProgressBarCircular.stories.ts

39 Component: Circular Progress Bar

---

src/ScrollBox.ts
src/stories/scrollBox/ScrollBoxSprite.stories.ts
src/stories/select/SelectGraphics.stories.ts

fixes #90
fixes #91
closes #92

Fix ScrollBox bugs

---

src/ScrollBox.ts

https://github.com/pixijs/ui/issues/102

102 Not full override of destroy method.

---

src/ScrollBox.ts

https://github.com/pixijs/ui/issues/99

99 wheel event listener not removed on ScrollBox destroy

---

src/Input.ts
src/stories/input/InputGraphics.stories.ts

Input: Changing the background Input lead to strange results. #108

---

src/CheckBox.ts
src/Input.ts

CheckBox: When update styles it is broken #110

---

src/DoubleSlider.ts
src/Slider.ts

Fix: Slider fill is visible when progress is close to edjes

---

src/List.ts
src/ScrollBox.ts
src/Select.ts

Add items to the Select element dynamically

---

src/ScrollBox.ts
src/stories/scrollBox/ScrollBoxProximity.stories.ts

- v8 version of https://github.com/pixijs/ui/pull/163

[v8] Feat: ScrollBox Item Proximity Event

---

src/ScrollBox.ts

- v8 version for https://github.com/pixijs/ui/pull/166

[v8] Feat: Expose trackpad's axis values and add a `scrollToPosition` method

---

src/ScrollBox.ts

- v8 version of https://github.com/pixijs/ui/pull/167

[v8] Fix: ScrollBox - Reset lastScrollX / lastScrollY on resize

---

src/SliderBase.ts

fixes https://github.com/pixijs/ui/issues/171

171 Error when using slider

---

src/SliderBase.ts

fixes https://github.com/pixijs/ui/issues/171

Fix #171 Error when using slider

---

src/Input.ts

I modified the Input class by adding the onInput method to react to changes in the input field value, including support for Input Method Editor (IME) input method, without disrupting the core logic of handling the input event.  It ensures reliable control and tracking of user-inputted data while preserving the integrity of the class functionality.

Feat: added OnInput event to support IME

---

src/ProgressBar.ts
src/Slider.ts
src/SliderBase.ts
src/stories/slider/SliderGraphics.stories.ts
src/stories/slider/SliderNineSliceSprite.stories.ts
src/stories/slider/SliderSprite.stories.ts

This PR adds support for steps on `Slider`. For now, it's implemented for single sliders only due to DoubleSlider being a bit more complex. We could try this implementation and see how it goes, then add it to more components.
Closes #37 #179

feat: Added slider step support

---

src/RadioGroup.ts

fix: RadioGroup labels type error

---

src/SliderBase.ts

fix: Interactivity for sliders outside bounds

---

src/ScrollBox.ts
src/stories/scrollBox/ScrollBoxGraphics.stories.ts

177 [Feature request]: Add scroll event listener to ScrollBox

---

src/ScrollBox.ts

This PR adds missing scroll event trigger during scrollbox drag and does a small clean up to existing scroll event functionality.

fix: Emit ScrollBox scroll event when dragging content

---

.gitignore
src/Input.ts

closes https://github.com/pixijs/ui/issues/195

195 Mask input as default

---

src/FancyButton.ts
src/stories/fancyButton/FancyButtonNineSlicePlaneSprite.stories.ts

This is a clone of #202 for v1.

Add Content Fitting Mode Option on Fancy Button

---

src/Input.ts

Fixes: https://github.com/pixijs/ui/issues/45

45 Text input may need to prevent default/bubble

---

src/Input.ts

This is a clone of #213 for v1

Feat: Add paste functionality to the input component (#213)

---

src/FancyButton.ts

fixes: https://github.com/pixijs/ui/issues/223

fix: 223 FancyButton loses disabled appearance when its views are replaced (test case attached)

---

src/CheckBox.ts

Fix for the issue https://github.com/pixijs/ui/issues/230

Fix CheckBox text positioning when assigned after construction
