pixijs/ui

- README.md
- package-lock.json
- package.json
- src/DoubleSlider.ts
- src/ScrollBox.ts
- src/Slider.ts
- src/stories/scrollBox/ScrollBoxGraphics.stories.ts
- src/stories/scrollBox/ScrollBoxSprite.stories.ts
- src/stories/select/SelectGraphics.stories.ts
- src/stories/select/SelectSprite.stories.ts
- src/stories/slider/DoubleSliderGraphics.stories.ts
- src/stories/slider/DoubleSliderSprite.stories.ts
- src/stories/slider/SliderGraphics.stories.ts
- src/stories/slider/SliderSprite.stories.ts
In pixi 7.1.1 global pointer events where added so that we didn't have to set `app.renderer.events.moveOnAll`
See [here](https://github.com/pixijs/pixijs/pull/9067) for details on the new events
This PR updates the library to use the new event
> Add globalpointermove

- src/Input.ts
- src/stories/input/InputGraphics.stories.ts
- src/stories/input/InputSprite.stories.ts
Closes #32
Now you can set padding same as css properties:
```
padding: 10 
// 10px for all 4 sides
```
This way we are saving backwards compatibility with the previous version
```
padding: [10, 20] 
// 10px top and bottom sides
// 20px for left and right sides
```
```
padding: [10, 20, 30, 40] 
// 10px top the side,
// 20px for the right side
// 30px for the bottom side
// 40px for the left side
```
```
new Input({
bg: Sprite.from('input.png'),
placeholder: 'Enter text',
padding: {
top: 11,
right: 11,
bottom: 11,
left: 11
} // alternatively you can use [11, 11, 11, 11] or [11, 11] or just 11
})
```
Stories also updated to test this edge cases.
> Improve padding setting for Input component

- src/Button.ts
- src/CheckBox.ts
- src/DoubleSlider.ts
- src/FancyButton.ts
- src/Input.ts
- src/Layout.ts
- src/MaskedFrame.ts
- src/ProgressBar.ts
- src/RadioGroup.ts
- src/ScrollBox.ts
- src/Select.ts
- src/Slider.ts
- src/Switcher.ts
There was an issue with examples styling that is fixed with this PR.
It removes "```" from the top and bottom of all examples
> Fix docs examples styling

- src/ScrollBox.ts
- src/utils/trackpad/Trackpad.ts
It's usual to rotate the whole game scene, when user's mobile device change orientation.
In order to adjust this situation, ScrollBox should use the touch point after `worldTransform.applyInverse`.
And then, because Trackpad is using shared instance `e.global` before, however after modifying the `_globalPosition` won't update automatically by the "shared global position" feature. It will cause list position jitter when user scroll and release and touch down again (just touch down, no move).
So Trackpad should update `_globalPosition` in the `pointerDown` method manually.
> Fix scroll direction problem when game rotated.

- src/ScrollBox.ts
- src/stories/scrollBox/ScrollBoxGraphics.stories.ts
- src/stories/scrollBox/ScrollBoxSprite.stories.ts
- src/utils/trackpad/SlidingNumber.ts
- src/utils/trackpad/Trackpad.ts
Closes #57
Added `disableEasing` option to ScrollBox
> 57 Implement smoothScroll disable option for ScrollBox

- src/ScrollBox.ts
We was using legacy 'mousewheel' & 'DOMMouseScroll' events...
fixes #86
> 86 ScrollBox not scrolling on mousewheel event in Firefox

- src/index.ts
heya
CircularProgressBar should be exported, doesn't it?
> fix: missing export for CircularProgressBar

- src/Input.ts
https://github.com/pixijs/ui/issues/98
> 98 Problem with the inputbox

- src/Input.ts
> Fix: Input field: keyboard hides on mobile devices #106

- package-lock.json
- package.json
- src/DoubleSlider.ts
- src/FancyButton.ts
- src/Input.ts
- src/ProgressBar.ts
- src/Slider.ts
- src/SliderBase.ts
- src/stories/fancyButton/FancyButtonNineSlicePlaneSprite.stories.ts
- src/stories/input/InputNineSlicePlane.stories.ts
- src/stories/progressBar/ProgressBarNineSlicePlane.stories.ts
- src/stories/progressBar/ProgressBarSprite.stories.ts
- src/stories/slider/DoubleSliderGraphics.stories.ts
- src/stories/slider/DoubleSliderNineSlicePlane.stories.ts
- src/stories/slider/DoubleSliderSprite.stories.ts
- src/stories/slider/SliderGraphics.stories.ts
- src/stories/slider/SliderNineSlicePlane.stories.ts
- src/stories/slider/SliderSprite.stories.ts
- src/utils/helpers/view.ts
- tsconfig.json
Integrate NineSlicePlane option to components:
closes #31 
closes #117
fixed #120
> Make Components responsive

- src/DoubleSlider.ts
- src/Slider.ts
- src/SliderBase.ts
> 124 Can't change default value to Slider after it has been created.

- src/ScrollBox.ts
> 100 pointertap event doesn't work for ScrollBox items on mobile phone

- src/ScrollBox.ts
- src/stories/scrollBox/ScrollBoxGraphics.stories.ts
- src/stories/scrollBox/ScrollBoxSprite.stories.ts
- Add `globalScroll` option, which when set to `false` only scroll when he pointer is over the top of the scroll box
- Add `shiftScroll` option, which when the scrollbox is horizontal forces the user to use the `shift + scroll` to move the scrollbox, better emulating how scroll boxes work on the browser
> Feat: add shift scroll and global scroll

- src/SliderBase.ts
- This prevents the interactions from being blocked by the overlaying slider handles and fill elements.
> Fix: Slider - Set eventMode to 'none' for slider handles and fill

- src/FancyButton.ts
- src/stories/fancyButton/FancyButtonBitmapText.stories.ts
- src/stories/fancyButton/FancyButtonDynamicUpdate.stories.ts
- src/stories/fancyButton/FancyButtonGraphics.stories.ts
- src/stories/fancyButton/FancyButtonHTMLText.stories.ts
- src/stories/fancyButton/FancyButtonIcon.stories.ts
- src/stories/fancyButton/FancyButtonNineSlicePlaneSprite.stories.ts
- src/stories/fancyButton/FancyButtonSprite.stories.ts
- src/utils/helpers/fit.ts
- Reset text/icon view scaling back to the default scale before doing the `fitToView` call to prevent the persistent of scale < 1 from the initial fitting.
eg. if the button default view texture has a width of 150 and the content text has a width of 200, it will apply 0.75 scaling to the text view to fit it within the button (assuming that the padding is 0). Then if the button width is then set to 250, the text will still remain at 0.75 despite that it no longer needed to be scaled down to fit within the button.
- A `ignoreRefitting` is provided in case the persistent scaling behaviour from before is preferred.
- Add the ability to pass in the base scale for text and icon at instantiation. This will be prioritise over the automatic extraction from the new text or icon views.
- Add the …
> Fix: Fancy Button Content Fitting

- src/FancyButton.ts
- src/stories/fancyButton/FancyButtonBitmapText.stories.ts
- src/stories/fancyButton/FancyButtonDynamicUpdate.stories.ts
- src/stories/fancyButton/FancyButtonGraphics.stories.ts
- src/stories/fancyButton/FancyButtonHTMLText.stories.ts
- src/stories/fancyButton/FancyButtonNineSlicePlaneSprite.stories.ts
- src/stories/fancyButton/FancyButtonSprite.stories.ts
- Allow the individually setting of default anchor of the content components, ie. the text and icon.
- If not specified, the anchor for both will be 0.5 on both axes.
- This can be useful for situations where you want to align the dynamic content to one side, eg. an localised text aligning left at a fix point on the button, pairing nicely with the offset options.
- Examples have been updated with these new anchor options.
> Feat: add text and icon default anchor options

- src/ScrollBox.ts
- src/stories/scrollBox/ScrollBoxProximity.stories.ts
- Checks and fires a proximity event when an item gets in and out of the proximity range.
- Proximity range can be customised, where 0 is where an item's bounds just touch the edge on the containing scroll box's bounds.
Resolves ticket https://github.com/play-co/pixi-ui/issues/26
> Feat: ScrollBox Item Proximity Event

- src/ScrollBox.ts
- Expose scrollbox trackpad's x and u axis values, allowing for direct getting and setting.
- Add a `scrollToPosition` method for scrolling to a given positional value set.
Resolves ticket #29.
> Feat: trackpad's axis values and add a `scrollToPosition` method

- src/ScrollBox.ts
The `lastScrollX` and `lastScrollY` values should be reset to `null` on `resize` (which also gets triggered when adding/removing items) to allow the redo of the proximity check.
> Fix: ScrollBox - Reset lastScrollX / lastScrollY on resize

- src/SliderBase.ts
This PR fixes a problem with sliders not being interactive outside bounds.
In the screenshot below, half of the slider cannot be dragged by user because it's outside view bounds.
Adding events to slider itself will take care of the problem and improve UX.
My approach is probably not very ideal but I still hope we manage to solve this somehow.
Probably fixes the problem that still persists in #136
> fix: Interactivity for sliders outside bounds

- src/RadioGroup.ts
It seems that nesting checkboxes without labels in RadioGroup results in a TypeError because labelTexts end up being undefined.
This PR fixes that.
> fix: RadioGroup labels type error

- src/Input.ts
> Feat: added OnInput event to support IME

- src/Slider.ts
- src/SliderBase.ts
- src/stories/slider/SliderGraphics.stories.ts
- src/stories/slider/SliderNineSlicePlane.stories.ts
- src/stories/slider/SliderSprite.stories.ts
> feat: Added slider step support 

- src/ScrollBox.ts
> Feat: Add scroll event listener to ScrollBox

- package-lock.json
- package.json
- src/List.ts
This PR adds generic types to `List` in order to behave just like `Container` in later versions of pixi.js v8.
Pixi dependency was updated intentionally as Container did not accept generic types in pixi.js v8.0.x.
> types: Updated List to accept generic types like Container

- src/DoubleSlider.ts
- src/FancyButton.ts
- src/Input.ts
- src/ProgressBar.ts
- src/ScrollBox.ts
- src/Slider.ts
in pixi v8 there is the get/set size functions that allow you to set both the width and height at the same time which is a bit more optimised than setting them individually
This PR ensure that any ui element that overrides width/height also overrides get/set size to ensure it works as expected
> fix: setSize not being overridden

- src/ScrollBox.ts
- src/stories/scrollBox/ScrollBoxSprite.stories.ts
This PR adds missing scroll event trigger during scrollbox drag and does a small clean up to existing scroll event functionality.
> fix: Emit ScrollBox scroll event when dragging content

- src/CheckBox.ts
- src/DoubleSlider.ts
- src/FancyButton.ts
- src/Input.ts
- src/ProgressBar.ts
- src/Select.ts
- src/SliderBase.ts
- src/Switcher.ts
- src/stories/progressBar/ProgressBarNineSlicePlane.stories.ts
- src/stories/progressBar/ProgressBarSprite.stories.ts
- src/utils/helpers/view.ts
Allow Texture instances to be supplied as an option for:
- FancyButton views
- ProgressBar background and fill
- Input background
This is a clone of #198 for v1.
> Allow Texture as the View Options

- src/Input.ts
This PR makes sure that Input cursor inherits text fill color even if it's something other than number (e.g. white).
Fixes https://github.com/pixijs/ui/issues/156
This is a clone of #200 for v1.
> fix(Input): Cursor should inherit text fill color of multiple formats

- src/Input.ts
- src/stories/input/InputGraphics.stories.ts
- src/stories/input/InputNineSlicePlane.stories.ts
- src/stories/input/InputSprite.stories.ts
This is a clone of #201 for v1.
> feat(Input): Added secure input functionality for typing passwords

- src/Input.ts
- src/stories/input/InputGraphics.stories.ts
This is a clone of https://github.com/pixijs/ui/commit/d4d455e30e7d93f78dc8ebb397bfde93609d46cf to v1.
> fix input mask

- src/Input.ts
Fixes: https://github.com/pixijs/ui/issues/45
> fix: 45 Text input may need to prevent default/bubble

- src/Input.ts
> Feat: Add paste functionality to the input component

- src/Input.ts
This PR adds a missing check in case text fill is null or undefined.
Essentially, it prevents `Color.isColorLike` from throwing and PR is not needed in v1 since we have a different approach there.
> fix(Input): Use default fill color as a color source if not set

- src/Input.ts
- src/List.ts
- src/ScrollBox.ts
- src/stories/list/ListGraphics.stories.ts
- src/stories/list/ListSprite.stories.ts
- src/stories/scrollBox/ScrollBoxDynamicDimensions.stories.ts
- src/stories/scrollBox/ScrollBoxGraphics.stories.ts
- src/stories/scrollBox/ScrollBoxProximity.stories.ts
- src/stories/scrollBox/ScrollBoxSprite.stories.ts
- src/utils/HelpTypes.ts
Added `bidirectionalScroll` to the `ScrollBoxOptions`, which allows the scroll-box to be scrolled both vertically and horizontally to accommodate overflows in both directions.
> Add the ability for the scrollbox to scroll in both direction

- src/ScrollBox.ts
- src/stories/list/ListSprite.stories.ts
- src/stories/scrollBox/ScrollBoxDynamicDimensions.stories.ts
- src/stories/scrollBox/ScrollBoxGraphics.stories.ts
- src/stories/scrollBox/ScrollBoxProximity.stories.ts
- src/stories/scrollBox/ScrollBoxSprite.stories.ts
- src/stories/switcher/Switcher.stories.ts
- src/utils/HelpTypes.ts
- This will make bi-directional scrolling an opt-in rather than enabled by default, ie. allowing the items to flow bi-directionally but only scrollable vertically when type is not specified.
> Hot-fix: Make ScrollBox Type Defaults to 'vertical'

- src/FancyButton.ts
> Fix small typo in FancyButton docs

- src/ScrollBox.ts
Now, after resizing an item, `scrollBox.resize(true)` to rearrange the items.
> fix: [ScrollBox] arrange children when force resizing.

- src/CheckBox.ts
Addresses an issue where the CheckBox label was mispositioned when its text was updated after the CheckBox's initial construction.
The label alignment is now handled by an `alignLabel` method, which is called both during initial setup and whenever the label text is changed. This ensures the label remains correctly positioned relative to the CheckBox.
Fixes #230
> fix: CheckBox text mispositioned when assigned after construction #230
